import static org.junit.Assert.assertEquals;

import org.junit.Test;

import testClasses.TestClass;


/**
 * Tests that contains at least one assert that fails.
 */
public class AssertFailTest 
{
	/*
	@Test
	public void assertFailAtTheEndTest() 
	{
		TestClass tc = new TestClass(99);
try {		assertEquals("one", tc.threePaths(1));} catch(org.junit.ComparisonFailure e){}
try {		assertEquals("two", tc.threePaths(2));} catch(org.junit.ComparisonFailure e){}
		//try {assertEquals("nine", tc.threePaths(3));} catch(Throwable e) {executionFlow.ConsoleOutput.showWarning("AssertFail("+e.getStackTrace()[2].getMethodName()+") - "+e.getMessage());}		// It will fail
	}*/
	
	@Test
	public void assertFailInTheMiddleTest() 
	{
		TestClass tc = new TestClass(99);
		//assertEquals("one", tc.threePaths(1));
try {		assertEquals("nine", tc.threePaths(3));		} catch(org.junit.ComparisonFailure e){}// It will fail
try {		assertEquals("two", tc.threePaths(2));} catch(org.junit.ComparisonFailure e){}
	}
	
	@Test
	public void t()
	{
		TestClass tc = new TestClass(99);
		try {
try {			assertEquals("one", tc.threePaths(1));} catch(org.junit.ComparisonFailure e){}
		} catch(Throwable t) {}
		try {
try {			assertEquals("o3213ne", tc.threePaths(4));} catch(org.junit.ComparisonFailure e){}
		} catch(Throwable t) {}
		try {
try {			assertEquals("two", tc.threePaths(2));} catch(org.junit.ComparisonFailure e){}
		} catch(Throwable t) {}
	}
}
